### ISSUE TITLE
question - how does this compare to react-native-paper ?

### ISSUE THREAD

**Issue by gcloeval** [codypearce/material-bread#321]
Hello,

Just wondering if you could provide some more details on how does this library compare with the above mentioned react-native-paper?
It appears this one is newer, which leads me to believe you must have had reasons to work on it and not use https://github.com/callstack/react-native-paper - so do you mind sharing pains? Or really any thoughts about when to use one or the other?

**Comment by codypearce** [comment]
Yeah it's a good question. There's about 4 main differences which I wrote about here https://material-bread.org/about. 

**Difficulties with Other libraries**

There's two main difficulties that I and a few colleagues ran into while using various react native material libraries. One is the lack of a complete solution, at the time there were three or four libraries, none of which covered all components found in the docs or that one might need. So this was a major motivator.

Second, customization with paper at the time was difficult, and at times impossible. For example trying to customize simple properties like button height, radio button padding, and text input line-height, was impossible. It was also made clear to us that this kind of customization was not a priority of the paper team, which led to us copying and heavily modifying many components into the project's themselves. At a certain point of copying and modifying it didn't make sense to use the library at all.  So a library that focused on allowing all types of customization would be beneficial, at least for the type of work we needed. 

**Uniqueness**

I think one of the biggest differences is that a main focus of Material Bread is on truly cross-platform. For example, all components should work on all react-native platforms, and there are specific web components provided as well.

Another major point that I wanted to include is providing detailed documentation with live demos. Many react native libraries do not provide live demos or give many use case examples, which means you're left to guesses how the library author thought you should use the components, instead of having easily copied examples for common cases.

**Conclusion**
I think Paper has addressed some of the problems we had at the beginning of the year, but looking at their issue log there's still a lot of confusion on customization, and that just won't work for many of the projects I contribute to.
